// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDZpXHCr0BZ22aigVNsEOjRzVxjpuYBU',
    appId: '1:972986084505:web:628210a18bd31c74b19c08',
    messagingSenderId: '972986084505',
    projectId: 'pbmproject-ee93a',
    authDomain: 'pbmproject-ee93a.firebaseapp.com',
    storageBucket: 'pbmproject-ee93a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQWQBZfN2SkNwebTKQPjE2GqHDq8HBTIw',
    appId: '1:972986084505:android:2b40ac602e1471f9b19c08',
    messagingSenderId: '972986084505',
    projectId: 'pbmproject-ee93a',
    storageBucket: 'pbmproject-ee93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCOhzx_cEzksE-bP40_HqAOlzYqqVEQmw',
    appId: '1:972986084505:ios:dd30cdaaf1de6e4ab19c08',
    messagingSenderId: '972986084505',
    projectId: 'pbmproject-ee93a',
    storageBucket: 'pbmproject-ee93a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCOhzx_cEzksE-bP40_HqAOlzYqqVEQmw',
    appId: '1:972986084505:ios:dd30cdaaf1de6e4ab19c08',
    messagingSenderId: '972986084505',
    projectId: 'pbmproject-ee93a',
    storageBucket: 'pbmproject-ee93a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoDZpXHCr0BZ22aigVNsEOjRzVxjpuYBU',
    appId: '1:972986084505:web:2799571bb5909d53b19c08',
    messagingSenderId: '972986084505',
    projectId: 'pbmproject-ee93a',
    authDomain: 'pbmproject-ee93a.firebaseapp.com',
    storageBucket: 'pbmproject-ee93a.appspot.com',
  );
}
